### ISSUE TITLE
What would you like to hear about from GitHub?

### ISSUE THREAD

**Issue by bryancross** [cubonetwork/cubo-github#1]
Bom Dia!

GitHub would like to hear from you, about what you'd like to hear about from us!  Starting in December, GitHub will be regularly hosting presentations on a wide variety of topics.  I've included a list of subjects to get things started, but we're also very interested in hearing from YOU about what you're interested in or have questions about.

Here's a list of potential topics.  We've delivered some of these to Cubo before, but there's no problem repeating topics to ensure that anyone who's interested gets a chance.  

**1) Secure Development with GitHub**

&nbsp;&nbsp;&nbsp;&nbsp;Learn how to use Protected Branches, Required Statuses, Code Owners, and other GitHub features to secure your codebase, prevent accidental or unauthorized commits to sensitive branches, and ensure quality with Continuous Integraiton

  **2) Introduction to Git and Github**

&nbsp;&nbsp;&nbsp;&nbsp;Learn what makes Git so special, and get a high-level view of how it works.  We'll also cover basic GitHub workflows using issues, pull requests, wikis, and GitHub pages.

  **3) GitHub and Data Science**

&nbsp;&nbsp;&nbsp;&nbsp;Designed for Data Scientists who are not hardcore software developers, this presentation relates the GitHub workflow to Data Science use cases.

  **4) Intro to GraphQL**

&nbsp;&nbsp;&nbsp;&nbsp;See what all the buzz around GraphQL is about.  Learn the basics, as well as how GraphQL can streamline your GitHub API calls

  **5) Intro to Continuous Integration with GitHub, Jenkins, and Amazon Codestar**

&nbsp;&nbsp;&nbsp;&nbsp;Learn how to create and deploy an Amazon Lambda function using Jenkins and [Amazon CodeStar](https://aws.amazon.com/codestar/)

Just let us know which of these you find interesting, and/or feel free to suggest any other topic!  

cc/ @harrisonleavitt

**Comment by danilodevhub** [comment]
People,

to vote in a potential topic give a 👍 (like) in the specific Comment bellow:

**Comment by danilodevhub** [comment]
**1) Secure Development with GitHub**

Learn how to use Protected Branches, Required Statuses, Code Owners, and other GitHub features to secure your codebase, prevent accidental or unauthorized commits to sensitive branches, and ensure quality with Continuous Integraiton

**Comment by danilodevhub** [comment]
**2) Introduction to Git and Github**

Learn what makes Git so special, and get a high-level view of how it works. We'll also cover basic GitHub workflows using issues, pull requests, wikis, and GitHub pages.

**Comment by danilodevhub** [comment]
**3) GitHub and Data Science**

Designed for Data Scientists who are not hardcore software developers, this presentation relates the GitHub workflow to Data Science use cases.

**Comment by danilodevhub** [comment]
**4) Intro to GraphQL**

See what all the buzz around GraphQL is about. Learn the basics, as well as how GraphQL can streamline your GitHub API calls

**Comment by danilodevhub** [comment]
**5) Intro to Continuous Integration with GitHub, Jenkins, and Amazon Codestar**

Learn how to create and deploy an Amazon Lambda function using Jenkins and Amazon CodeStar

**Comment by frichardben** [comment]
GitHub and Data Science

**Comment by bryancross** [comment]
@danilodevhub Finally got my [AWS Lambda Deployment](https://drive.google.com/file/d/1G4zyJ44aVdxUBWptV-2x6M94Ox3ThOFJ/view?usp=sharing) deck uploaded.  Sorry for the delay 😸 

BTW, if you're doing stuff with AWS build chain, you might be interested in [this repo](https://github.com/toricls/github-codebuild-integration).  Seems to be a pretty solid toolset for integrating CodeBuild with GitHub status checks, allowing for feedback on the Pull Request.

**Comment by danilodevhub** [comment]
Very Good and Thanks @bryancross 👏 
It's a good moment to get it, because since we segregate our serverless application it broken our CI/CD =/

Sharing with team... @mikailcf @Xhamps @LFeh @mcamendola @CarolPC @wenderjean ;)
